# docker-compose.dev.yml
version: "3.9"

services:
  mysql-user:
    image: mysql:8.0
    container_name: nihil_mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nihil_user_dev
    ports:
      - "3309:3306"         # avoid clashes with other local MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - mysql_user_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  mysql-post:
    image: mysql:8.0
    container_name: nihil_mysql_post
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nihil_post_dev
    ports:
      - "3310:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - mysql_post_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  seed-user:
    image: node:24-alpine3.21
    depends_on:
      mysql-user:
        condition: service_healthy
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      USER_DATABASE_URL: mysql://root:root@mysql-user:3306/nihil_user_dev
      SKIP_CLEANUP: "false"
      NODE_ENV: dev
    command: sh -lc "npm ci && npm run --workspaces prisma:generate && npm run prisma:db:push --workspace=user && npm run prisma:db:seed --workspace=user"

  seed-post:
    image: node:24-alpine3.21
    depends_on:
      mysql-post:
        condition: service_healthy
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      POST_DATABASE_URL: mysql://root:root@mysql-post:3306/nihil_post_dev
      SKIP_CLEANUP: "false"
      NODE_ENV: dev
    command: sh -lc "npm ci && npm run --workspaces prisma:generate && npm run prisma:db:push --workspace=post && npm run prisma:db:seed --workspace=post"

volumes:
  mysql_user_data:
  mysql_post_data:
